### PR TITLE
Simplify session 3

### PR DESCRIPTION
**Pull request by Talexis77**

### CODE REVIEW

**Comment by irisoren-sg** [comment]
@Talexis77 
The version that you sent was still using the old Benefit* data. We created new data in the branch rework_session3. When I merged the latter branch into this, it would not run. It required a set of changes to get the new worked_solution to knit properly. Can you confirm that all the files in R/ and in the main project directory work properly for you, and if so, merge?

**Comment by Talexis77** [comment]
@irisoren-sg I think I have probably misunderstood how github works here. I thought I would be able to push my changes only and then combine with the other branch that had the new version of the data (rework_session3). Looking at the new data it does look like my rename statements are the wrong way around (I did old_name = new_name which isn't right I think). Is that the only part that was wrong? If you have already changed it so it runs correctly could you push that version instead?

Sorry for creating confusion, happy to fix this myself if you don't already have a working version!

**Comment by irisoren-sg** [comment]
The rename is now 
rename(new_name = old_name)

**Comment by Talexis77** [comment]
@irisoren-sg thanks for explaining. I pulled it again and everything runs and looks as expected so I have merged the pull request

**Pull request merged**
