### PR TITLE
Make material suitable for self-study

### PR DESCRIPTION
**Pull request by irisoren-sg**
Add a section on how to use the material
This includes a link to video, currently hoseted on Teams The link should be changed when hosting location is finalised.

The rest of the README was reformatted for lists to appear correctly in RStudio.

### CODE REVIEW

**Comment by irisoren-sg** [comment]
@jayware9 Could you have a look at the changes to the README and the linked demo video.

Is there anything else that we need in the video to make the material suitable for self-study?

We need to decide where to host the video. I'd prefer to keep it out of the repo as it is a large file (there are ways around this, but complicated). If we put it on YouTube, we could automatically add subtitles. 

Thoughts?

**Comment by jayware9** [comment]
@irisoren-sg this is looking good and think everything is covered. Agree about keeping the video out of the repo. Youtube might be the best option, maybe as an unlisted video, though I've no experience in uploading. Alternative might be just using sharepoint and looks like there's an option for auto-generating captions as well (though not sure if these are as accurate as what google/youtube can generate)

**Comment by irisoren-sg** [comment]
Add R installation instructions to README

**Comment by irisoren-sg** [comment]
@jayware9 I have added an image of RStudio window to README, and some text. Could you have a look, comment, or merge if happy?

**Comment by jayware9** [comment]
This looks great, I'll merge it in

**Pull request merged**
